apiVersion: v1
kind: Service
metadata:
 name: demo-app-service
 namespace: demo-app
spec:
 ports:
 - port: 8080
   targetPort: 8080
   nodePort: 31001
   protocol: TCP
 type: NodePort
 selector:
   app: demo-app-deployment