apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: demo-app-deployment
spec:
 selector:
   # Selector for Pods
   app: demo-app
 ports:
   # Port Map
 - port: 30000
   targetPort: 8080
   protocol: TCP
 type: LoadBalancer